name: ExpressionWorkflow
run-name: expressions-workflow
on: push
env:
  ENVIRONMENT: staging
  GREATER_THAN: ${{ 34 > 18 }}
  BRANCH_NAME: ${{ github.ref_name }}

jobs:
  deploy-staging:
    if: ${{ env.ENVIRONMENT == staging }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to stating...
        run: echo Deploying to $ENVIRONMENT

  deploy-prod:
    if: ${{ env.ENVIRONMENT == production }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to production...
        run: echo Deploying to $ENVIRONMENT

  greater:
    if: ${{ env.GREATER_THAN }}
    runs-on: ubuntu-latest
    steps:
      - name: Print is greater
        run: echo The age is enough $GREATER_THAN

  run-unit-test:
    if: ${{ contains(env.BRANCH_NAME, 'actions') }}
    runs-on: ubuntu-latest
    steps:
      - name: run-unit
        run: echo Running test in $BRANCH_NAME branches

  print-all-vars:
    runs-on: ubuntu-latest
    steps:
      - name: Printing...
        run: |
          echo $ENVIRONMENT
          echo $GREATER_THAN
          echo $BRANCH_NAME
