name: ExpressionWorkflow
run-name: expressions-workflow
on: push

env:
  ENVIRONMENT: staging
  BRANCH_NAME: ${{ github.ref_name }}

jobs:
  deploy-staging:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to stating...
        if: ${{ env.ENVIRONMENT == 'staging' }}
        run: echo Deploying to $ENVIRONMENT

  deploy-prod:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to production...
        if: ${{ env.ENVIRONMENT == 'production' }}
        run: echo Deploying to $ENVIRONMENT

  greater:
    if: ${{ 34 > 18 }}
    runs-on: ubuntu-latest
    steps:
      - name: Print is greater
        run: echo The age is enough $GREATER_THAN

  run-unit-test:
    if: ${{ contains(github.ref_name, 'actions') }}
    runs-on: ubuntu-latest
    steps:
      - name: run-unit
        run: echo Running test in $BRANCH_NAME branches

  print-all-vars:
    runs-on: ubuntu-latest
    steps:
      - name: Printing...
        run: |
          echo $ENVIRONMENT
          echo $GREATER_THAN
          echo $BRANCH_NAME
